// Package session holds corral's own domain vocabulary for a supervised
// Claude Code session: the spec used to spawn one, its persisted record,
// and its event-log vocabulary. It exists precisely so internal/store,
// internal/supervisor, and internal/api can all depend on a shared set of
// types without depending on each other (design doc §1).
package session

// Mode is how a session's PTY is being used. ModeInteractive spawns claude
// under a PTY (M1); ModeHeadless is real as of M4 (design doc §5): a
// one-shot `claude -p` invocation captured via plain pipes, no PTY, no
// Screen. supervisor.Registry.Spawn and BuildArgv both dispatch on this
// field.
type Mode string

const (
	ModeInteractive Mode = "interactive"
	ModeHeadless    Mode = "headless"
)

// Spec is the complete, self-contained description of a session to spawn
// (design doc §7.1). It carries everything supervisor/spawn.go needs to
// build argv and env — nothing about spawning is inferred from ambient
// process state.
type Spec struct {
	ID             string            // uuidv4, generated by corral; == claude --session-id on first spawn
	Name           string            // unique handle; default "<basename(cwd)>-<n>"
	Mode           Mode              //
	Cwd            string            // absolute, must exist and be a directory
	ClaudeBin      string            // absolute, resolved via LookPath if needed
	Model          string            // "" = omit --model
	SettingSources string            // value for --setting-sources
	SettingsPath   string            // pinned settings file (written before spawn)
	ExtraArgs      []string          // reserved; empty in M1
	Env            map[string]string // the complete child environment. Nothing else is inherited.
	Rows, Cols     uint16            // initial PTY size (default 40x120 when nothing is attached); unused for ModeHeadless
	ResumeFrom     string            // "" = fresh (--session-id); else --resume <this>

	// Prompt is the one-shot -p prompt (design doc §5.1). Meaningful only
	// for ModeHeadless; empty for ModeInteractive. BuildArgv's persisted
	// (redact=true) copy replaces this with a byte-count placeholder
	// rather than the real text — not because it is secret, but to avoid
	// putting an arbitrarily large prompt into the sessions.argv column.
	Prompt string

	// PermissionMode is the value for --permission-mode; "" omits the flag
	// entirely (design doc §5.3). It applies to both interactive and
	// headless sessions. This is the flag that
	// makes bypassPermissions reachable, so it must only ever be populated
	// from a user- or env-file-resolved setting (config.Session.
	// PermissionMode / repo_allowlist.go's rule) — never from anything
	// repo-controlled.
	PermissionMode string

	// DepWorktrees is a pre-marshaled JSON array of the task's resolved
	// dependency worktrees (design doc §6.2): each element is
	// {"name","worktree","branch"} for one dependency task that has a
	// non-empty resolved worktree. "" means none (no worktree-using
	// dependency, or the task itself has no dependencies). Headless-only.
	// BuildEnv (supervisor/spawn.go) copies this verbatim into the child's
	// CORRAL_DEP_WORKTREES environment variable when non-empty — this is
	// the ONLY place it is consumed; never written into Env directly by a
	// caller, matching BuildEnv's "returned map is always exactly ..."
	// invariant for CORRAL_SESSION_ID/CORRAL_SOCK.
	DepWorktrees string
}
