// Package session holds corral's own domain vocabulary for a supervised
// Claude Code session: the spec used to spawn one, its persisted record,
// and its event-log vocabulary. It exists precisely so internal/store,
// internal/supervisor, and internal/api can all depend on a shared set of
// types without depending on each other (design doc §1).
package session

// Mode is how a session's PTY is being used. M1 only ever spawns
// ModeInteractive; ModeHeadless is reserved for a later milestone.
type Mode string

const (
	ModeInteractive Mode = "interactive"
	ModeHeadless    Mode = "headless"
)

// Spec is the complete, self-contained description of a session to spawn
// (design doc §7.1). It carries everything supervisor/spawn.go needs to
// build argv and env — nothing about spawning is inferred from ambient
// process state.
type Spec struct {
	ID             string            // uuidv4, generated by corral; == claude --session-id on first spawn
	Name           string            // unique handle; default "<basename(cwd)>-<n>"
	Mode           Mode              //
	Cwd            string            // absolute, must exist and be a directory
	ClaudeBin      string            // absolute, resolved via LookPath if needed
	Model          string            // "" = omit --model
	SettingSources string            // value for --setting-sources
	SettingsPath   string            // pinned settings file (written before spawn)
	ExtraArgs      []string          // reserved; empty in M1
	Env            map[string]string // the complete child environment. Nothing else is inherited.
	Rows, Cols     uint16            // initial PTY size (default 40x120 when nothing is attached)
	ResumeFrom     string            // "" = fresh (--session-id); else --resume <this>
}
